[package]
name = "junitxml2subunit"
version = "0.1.0"
authors = ["Matthew Treinish <mtreinish@kortar.org>"]

[dependencies]
subunit-rust = "0.1.1"
quick-xml = "0.12.1"
chrono = "0.4"
num-traits = "0.2"
