name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        components: rustfmt
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Build
      run: cargo build --verbose
    - name: Rust fmt
      run: cargo fmt -- --check
    - name: Clippy
      run: cargo clippy -- -D warnings
    - name: Install test deps
      run: |
        set -e
        python -m pip install -U testtools python-subunit os-testr stestr
    - name: Run tests
      run: |
        set -e
        cd tests
        python -m subunit.run test_command | subunit-trace
